#!/bin/bash

LUNEOS_ROOT="$(dirname "$(readlink -f "${0}")")"
REPO_ROOT="${LUNEOS_ROOT}/../.."

# Test if the folder exists
if ! [ -d $REPO_ROOT/.repo/local_manifests/ ]; then
    mkdir $REPO_ROOT/.repo/local_manifests/
fi

if [ -f $LUNEOS_ROOT/luneos.xml ]; then
    # Link the luneos manifest to the local_manifests folder
    ln $LUNEOS_ROOT/luneos.xml $REPO_ROOT/.repo/local_manifests/luneos.xml
fi
